### ISSUE TITLE
PGO Configs

### ISSUE THREAD

**Issue by BobMacpherson** [RobRich999/Chromium_Misc#1]
Could you show how you get chromium to build with pgo?

**Comment by RobRich999** [comment]
For Linux you can use the in-tree profile provided by Chrome OS for the Android project.

The profile is regularly updated, though with LLVM it does not have to be a 100% match to still provide usable profiling information, so do not be concerned if it is slightly behind your source.

Set either of these build arguments when building Chromium on Linux:

clang_use_default_sample_profile = true

or

clang_sample_profile_path = "//chrome/android/profiles/afdo.prof"

**Comment by BobMacpherson** [comment]
What about building with "pgo_build=true" "chrome_pgo_phase=1" "chrome_pgo_phase=2" and "pgo_data_path"?
I've been trying to generate and use a PGO profile using these configs but it throws out literally every error thats possible in the BUILD.gn when attempting to generate the pgo

**Comment by RobRich999** [comment]
The PGO build arguments are leftovers from MSVC for Windows build. They basically have been deprecated since the project migrated to LLVM (Clang+LLD) for building on Windows IMO.

If you really want to generate a local instrumented build to profile, then you are going to need to modify chromium/src/build/config/compiler/BUILD.gn to insert the correct Clang PGO build flags and manually change the flags to do a two-stage build. Do an instrumented build, run it to generate a profile, then build again.

https://clang.llvm.org/docs/UsersManual.html#profile-guided-optimization

YMMV. I have not tried it on Linux or similar. Last time I tried it on Windows, IIRC, it was not generating the desired profile data. Thinking I also had to modify LLD to disregard duplicate symbols.

Are you building with link time optimization? If so, you might not find a significant performance difference using PGO anyway.

use_thin_lto = true
thin_lto_enable_optimizations = true

I largely do PGO for Linux builds because the profile is already there to use. ;)

**Comment by BobMacpherson** [comment]
> then you are going to need to modify chromium/src/build/config/compiler/BUILD
I do believe it is already nativly supported in src/build/config/compiler/pgo, using the aforementioned switches, which was why initially was trying to use them.

> Are you building with link time optimization?
Yes, i'm using thin_lto and LLD

**Comment by RobRich999** [comment]
Quick update. I have not forgotten about ya'. ;) Polly builds on Windows have been taking much of my Chromium time.

I will try to take a look at generating a localized PGO build soon, at least for Linux. ChromeOS does it, so apparently it is working somehow. ;)

**Comment by BobMacpherson** [comment]
Any update on this?

**Comment by mikhailnov** [comment]
In 2021 setting `is_official_build=true` automatically turns on PGO with bundled profiling data and clang. See https://chromium.googlesource.com/chromium/src/+/lkgr/build/config/compiler/pgo/pgo.gni and https://chromium.googlesource.com/chromium/src/+/lkgr/build/config/compiler/pgo/BUILD.gn

**Comment by LifeIsStrange** [comment]
@mikhailnov is linux pgo supported by default? https://www.phoronix.com/scan.php?page=news_item&px=Chrome-85-Clang-PGO

**Comment by mikhailnov** [comment]
> @mikhailnov is linux pgo supported by default? https://www.phoronix.com/scan.php?page=news_item&px=Chrome-85-Clang-PGO

Yes, but only of you use bundled clang. Otherwise PGO data will be for another compiler and will not work.

**Comment by LifeIsStrange** [comment]
I'm not sure to understand:
What you mean is that chromium ship with its own clang.
But one can manually make chromium use an external clang instead of the bundled one?
If so do you know if linux distros in general (or at least archlinux) make chrome use its own bundled clang by default?

**Comment by mikhailnov** [comment]
18 февр. 2022 г. 01:47:22 LifeIsStrange ***@***.***>:

> I'm not sure to understand:
> What you mean is that chromium ship with its own clang.
Yes
> But one can manually make chromium use an external clang instead of the bundled one?
Yes. See https://abf.io/import/chromium-browser-stable/blob/77afa73de909b1ca7a2f745e76c8a9bd59b5ef93/chromium-browser-stable.spec#lc-515 and some lines bellow.
> If so do you know if linux distros in general (or at least archlinux) make chrome use its own bundled clang by default?
No. Arch Linux does not.
ROSA Linux spec by the link above allows to turn on using bundled clang, but it is turned off by default. It was not useable because x86_32 (32 bit) packages cpuld not be built using it, now I stopped building 32 bit Chromium, bundled clang can be reconsidered, thanks for remembering me about it ))
I remember that Ubuntu's snap used bundled clang, maybe it still uses it, but I would hardly call that a distro package.
